import Head from 'next/head'
import Navigation from './Navigation'
import Footer from './Footer'

export default function Layout({children}) {
  return (
    <div>
      <Head>
        <title>Rockshop - Choose your guitars</title>
        <meta name="description" content="Generated by Marcel Birkhahn" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      {children}
      <Footer />
    </div>
  )
}